### ISSUE TITLE
Add you company logo to the MN site!

### ISSUE THREAD

**Issue by samccone** [rapid7/marionette.carpenter#16]
Nice meeting you guys :heart:  add your logo to our site!!!

https://github.com/marionettejs/marionettejs.com/blob/master/src/sections/_companies.jade

**Comment by mbuck-r7** [comment]
Yeah good call! I'll do that right now.

Thanks again for coming out! Great meeting you. Feel free to hit us up if you have any time to hang before you head back!

**Comment by mbuck-r7** [comment]
Added with marionettejs/marionettejs.com#363.
