### ISSUE TITLE
Unable to npm install 

### ISSUE THREAD

**Issue by claughlin-r7** [rapid7/marionette.carpenter#24]
Unable to install npm packages due to issues with third party packages. strscan is a dependance of grunt-eco but it seems that strscan has been removed from npm and thus blocks the install and prevents grunt build.

**Comment by claughlin-r7** [comment]
Package seems to be back in the registry closing issue.

**Comment by mbuck-r7** [comment]
Cool! Yup, just verified on a fresh clone.
