### ISSUE TITLE
Latest Release

### ISSUE THREAD

**Issue by abologna-r7** [rapid7/marionette.carpenter#34]
When will Marionette Carpenter release to next version? Also there should be milestones being generated :)

**Comment by claughlin-r7** [comment]
:+1
We have some needed changes for depending apps we should release soon

Sent from my iPhone

On 29 Dec 2015, at 16:59, Antonio Bologna <notifications@github.com<mailto:notifications@github.com>> wrote:


When will Marionette Carpenter release to next version? Also there should be milestones being generated :)

-

**Comment by farias-r7** [comment]
I'll aim to add release steps to the Readme and release.

**Comment by farias-r7** [comment]
https://github.com/rapid7/marionette.carpenter/releases/tag/0.0.3

Cheers!
