### ISSUE TITLE
region.show(controller) pattern is incompatible with stock Marionette

### ISSUE THREAD

**Issue by jvennix-r7** [rapid7/marionette.carpenter#5]
In Pro, we use some extensions from `backbone-rails` to let us `show()` a controller directly on a region. These are not available in stock Marionette, so currently stock Marionette boilerplate would look like:

    var controller = new Marionette.Carpenter(...);
    this.myRegion.show(controller.getMainView())

This is suboptimal because `getMainView` is undocumented and I wouldn't think to look for it. We should optimize for the common case (of no `backbone-rails` extensions) with something like:

    var view = Marionette.Carpenter(...);
    this.myRegion.show(view);
    view.controller.on('blah', function(){  });

Or perhaps with a separate `create()` method:

    var view = Marionette.Carpenter.create(...);
    this.myRegion.show(view.controller);

**Comment by farias-r7** [comment]
I agree. So to recap a user can render one of two ways.

The first is initialize the controller and specify a region.

```
 new Marionette.Carpenter.Controller({
      title: 'Woodworkers',
      'static': true,
      region: new Backbone.Marionette.Region({
        el: '#woodworkers-table-region'
      }),
      columns: [
        { attribute: 'first_name' },
        { attribute: 'last_name' }
      ],
      collection: c
    });
```

The second is 

```
 var view = new Marionette.Carpenter.create({
      title: 'Woodworkers',
      'static': true
      columns: [
        { attribute: 'first_name' },
        { attribute: 'last_name' }
      ],
      collection: c
    });
app.myRegion.show(view)
```
